FROM oven/bun:1.3.14-alpine AS build-stage
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install
COPY . .
ARG BUILD_HASH
ENV VITE_BUILD_HASH=${BUILD_HASH}
RUN bun run build-only --mode production

FROM nginx:stable-alpine-slim AS production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY default.conf /etc/nginx/conf.d/default.conf