FROM oven/bun:1.1.12-alpine as build-stage
WORKDIR /app
COPY package.json bun.lockb ./
RUN bun install
COPY . .
RUN bun run build-only --mode production

FROM nginx:stable-alpine-slim as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY default.conf /etc/nginx/conf.d/default.conf