name: CI/CD Sapa Mitra Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["closed"]
    branches: ["main"]
permissions:
  contents: read
  packages: write

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry (GHCR)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push Docker Image
        run: |
          BUILD_HASH=$(git rev-parse --short HEAD)
          docker build --no-cache --build-arg BUILD_HASH=$BUILD_HASH -t sapa-mitra-frontend -f Dockerfile.production .
          docker tag sapa-mitra-frontend ghcr.io/bps-kota-bontang/sapa-mitra-frontend:latest
      - name: Push to GitHub Container Registry (GHCR)
        run: |
          docker push ghcr.io/bps-kota-bontang/sapa-mitra-frontend:latest